"""Initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-04-25 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_is_active", "users", ["is_active"], unique=False)

    op.create_table(
        "newsletters",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("send_date", sa.Date(), nullable=False),
        sa.Column("sequence_num", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("level_at_send", sa.Integer(), nullable=False),
        sa.Column("words", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=20), server_default="scheduled", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "send_date", "sequence_num", name="uq_newsletter_user_date_seq"),
    )
    op.create_index("ix_newsletters_user_send_date", "newsletters", ["user_id", "send_date"], unique=False)

    op.create_table(
        "sent_words",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("newsletter_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("level_at_send", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["newsletter_id"], ["newsletters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "word", name="uq_sent_words_user_word"),
    )
    op.create_index("ix_sent_words_user_sent_at", "sent_words", ["user_id", "sent_at"], unique=False)
    op.create_index("ix_sent_words_user_word_lower", "sent_words", [sa.text("lower(word)"), "user_id"], unique=False)

    op.create_table(
        "feedback_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("newsletter_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("level_adjusted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["newsletter_id"], ["newsletters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("ix_feedback_tokens_expires", "feedback_tokens", ["expires_at"], unique=False)
    op.create_index("ix_feedback_tokens_token", "feedback_tokens", ["token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_feedback_tokens_token", table_name="feedback_tokens")
    op.drop_index("ix_feedback_tokens_expires", table_name="feedback_tokens")
    op.drop_table("feedback_tokens")
    op.drop_index("ix_sent_words_user_word_lower", table_name="sent_words")
    op.drop_index("ix_sent_words_user_sent_at", table_name="sent_words")
    op.drop_table("sent_words")
    op.drop_index("ix_newsletters_user_send_date", table_name="newsletters")
    op.drop_table("newsletters")
    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
